### ISSUE TITLE
README Neovim example to run leptosfmt on save

### ISSUE THREAD

**Issue by ChristopherPerry6060** [bram209/leptosfmt#79]
Can PR a hacky autocommand if it would be useful

**Comment by SnowdenWintermute** [comment]
I wouldn't mind taking a look at such a command if you have one :)

**Comment by bram209** [comment]
hi, feel free to submit a PR with some notes for fellow (neo)vim users ; )

**Comment by bram209** [comment]
in #88 I implemented support for calling `rustfmt`. This enables you to configure rust analyzer to call `leptosfmt` instead of `rustfmt` and should work fine with LSP compatible editors.

I am closing this issue for now, but feel free to make a PR to add more options to the documentation of how `leptosfmt` may be used.
